[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-ito_os.json"

[target.'cfg(any(target_arch = "x86_64", target_arch = "x86"))']
runner = "bootimage runner"