[build]
target = "x86_64-ito_os.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(all(target_arch = "x86_64", target_os = "none"))']
runner = "bootimage runner"
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-zmax-page-size=0x1000",
]